/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cConverter;

/**
 *
 * @author uncommonStudent
 */
public class cConverter extends javax.swing.JFrame {
  double Zimbabwe_Gold	= 12.7;        
  double Botswana_pula = 33.78;
  double Angolan_AOA = 21.75; 
  double Egyptian_pound	= 23.56;         
  double Liberian_LRD =23.67;
  double Mozambican_MZN = 20.4;
  double Namibian_NAD = 23.89;	         
  double SouthAfrican_ZAR = 13.78;     
  double Tanzanian_TZS = 12.56;    
  double Zambian_ZMW   = 10.45;  

   

    /**
     * Creates new form cConverter
     */
    public cConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboCurrency = new javax.swing.JComboBox<>();
        jLabConv = new javax.swing.JLabel();
        jtxtConvert = new javax.swing.JTextField();
        jbtnExit = new javax.swing.JButton();
        jbtnConv = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Currency Converter");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 10));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jComboCurrency.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jComboCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Zimbabwe Gold\t       ", "Botswana pula\t       ", "Angolan kwanza         ", "Egyptian pound\t         ", "Liberian dollar\t         ", "Mozambican metical  ", "Namibian dollar\t         ", "South African rand      ", "Tanzanian shilling       ", "Zambian kwacha        ", "       ", " " }));
        getContentPane().add(jComboCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 460, 50));

        jLabConv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabConv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        getContentPane().add(jLabConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 460, 50));

        jtxtConvert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 5));
        getContentPane().add(jtxtConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 460, 50));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 5));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jbtnConv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnConv.setText("Convert");
        jbtnConv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 5));
        jbtnConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 5));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jtxtConvert.setText(null);
        jLabConv.setText(null);
        jComboCurrency.setSelectedItem(0);
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvActionPerformed
        // TODO add your handling code here:
// Ensure input is valid
    try {
        double British_Pound = Double.parseDouble(jtxtConvert.getText());
        String cConvert1 = "";

        String selectedCurrency = jComboCurrency.getSelectedItem().toString().trim();

        if (selectedCurrency.equals("Zimbabwe Gold")) {
            cConvert1 = String.format("Zig %.2f", British_Pound * Zimbabwe_Gold);
        } else if (selectedCurrency.equals("Botswana pula")) {
            cConvert1 = String.format("Pula %.2f", British_Pound * Botswana_pula);
        } else if (selectedCurrency.equals("Angolan kwanza")) {
            cConvert1 = String.format("Ang %.2f", British_Pound * Angolan_AOA);
        } else if (selectedCurrency.equals("Egyptian pound")) {
            cConvert1 = String.format("Pound %.2f", British_Pound * Egyptian_pound);
        } else if (selectedCurrency.equals("Liberian dollar")) {
            cConvert1 = String.format("Lib %.2f", British_Pound * Liberian_LRD);
        } else if (selectedCurrency.equals("Mozambican metical")) {
            cConvert1 = String.format("Metical %.2f", British_Pound * Mozambican_MZN);
        } else if (selectedCurrency.equals("South African rand")) {
            cConvert1 = String.format("Rand %.2f", British_Pound * SouthAfrican_ZAR);
        } else if (selectedCurrency.equals("Tanzanian shilling")) {
            cConvert1 = String.format("Shilling %.2f", British_Pound * Tanzanian_TZS);
        } else if (selectedCurrency.equals("Zambian kwacha")) {
            cConvert1 = String.format("Kwacha %.2f", British_Pound * Zambian_ZMW);
        } else {
            cConvert1 = "Please select a valid currency!";
        }

        // Display result
        jLabConv.setText(cConvert1);

    } catch (NumberFormatException e) {
        jLabConv.setText("Invalid input! Enter a valid number.");
    }
         
    }//GEN-LAST:event_jbtnConvActionPerformed

    /**
     * 
       
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboCurrency;
    private javax.swing.JLabel jLabConv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnConv;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtConvert;
    // End of variables declaration//GEN-END:variables
}
